#!/bin/bash

# Description - Check PulseAudio daemon
# Copyright (C) 2010 Intel Corporation
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Authors:
#       Wang, Jing J  <jing.j.wang@intel.com>
# Changlog:
# Wan Shuang 2010/08/03
#   For pulseaudio, test cases need to be run in the pulseaudio session user.
#   This util will find pulseaudio run in which user session and then
#   switch to that user to run the test case
#!/bin/sh

if [ -z "$1" ]; then
    echo "Warning: Please specify execution command"
    exit 1
fi

# Find the session user from proc file of process pulseaudio
usr=`cat /proc/$(pidof pulseaudio)/environ | tr "\0" "\n" | grep USER= | cut -d "=" -f2`

if [ $? -ne 0 ]; then
    echo "Error: Failed to find proc information of process pulseaudio"
    echo "Please check that if pulseaudio is running or if proper permission is granted"
    exit 1
fi

su -l $usr -c "$*"

