#!/bin/sh
#
# Copyright (C) 2010, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307 USA.
#
# Authors:
#       Zhang Jingke  <jingke.zhang@intel.com>
# Date Created: 2010/01/12
#
# Modifications:
#          Modificator  Date
#          Content of Modification
#

# Set environment variable here to specify the BT autotest server's MAC address
SERV_BD_ADDR="00:0A:94:03:EB:EB"
# Server type, we support "computer", "headset", "phone" and "keyboard or mouse" here. 
SERV_BD_TYPE="computer"  


DATA_DIR="./data"
FTP_CLIENT="${DATA_DIR}/ftp-client"
PBAP_CLIENT="${DATA_DIR}/pbap-client"
TEST_ADAPTER="${DATA_DIR}/test-adapter"
TEST_DEVICE="${DATA_DIR}/test-device"

ROOT_PASS="123456"
TEST_NAME_STRING="default"
TEST_TEXT_FILE="${DATA_DIR}/text_file_512k"
export PATH=$PATH:/sbin/:/usr/sbin/:./data/

# init hci status on client
hciconfig hci0 piscan

