#!/usr/bin/python
## Copyright (C) 2008-2010, Intel Corporation.
# DESCR: oFono sms test script
# TIMEOUT:60
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307 USA.
#
# Authors:
#       Li,Lily  <li.l.li@intel.com>
#

import sys
import dbus

def print_useage(s):
	print "Useage: %s <number> <vcard file dir+fileName>" % (s)
	sys.exit(1);
	
if len(sys.argv) < 3 and len(sys.argv) != 2:
	print_useage(sys.argv[0])

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()
path = modems[0][0]

manager = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.SmartMessaging')

vcard = file(sys.argv[2]).read()
try:
  path = manager.SendBusinessCard(sys.argv[1], vcard)
  print path
  sys.exit(0)
except dbus.DBusException, e:
		print "Unable to send Vcard: ", e
		sys.exit(1)  


print "Unkonown command:"
sys.exit(1)

