tabSMS.gbMessage1.leMessageSender.text = "12345";
tabSMS.gbMessage1.leSMSClass.text = "2";
tabSMS.gbMessage1.teSMSText.setPlainText("Sent from phonesim to test long message.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz");
tabSMS.gbMessage1.pbSendSMSMessage.click();
