#!/usr/bin/python
# Copyright (C) 2008-2010, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307 USA.
#
# Authors:
#       Li,Zhigang  <zhigang.li@intel.com>
#
#

import sys
import dbus

def print_useage(s):
        print "Usage: %s poweron" % (s)
	print "Usage: %s settopic <name>" % (s)
	print "Usage: %s properties" % (s)

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()
path=modems[0][0]

cb = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.CellBroadcast')

if len(sys.argv) < 2:
	print_useage(sys.argv[0])
        sys.exit(1);

if sys.argv[1] == 'poweron':
	try:
		cb.SetProperty("Powered",dbus.Boolean(1))
                sys.exit(0)
        except dbus.DBusException, e:
		print " unable to power cbs %s" % e
                sys.exit(1)

if sys.argv[1] == 'settopic':
	try:
		cb.SetProperty("Topics", sys.argv[2])
		sys.exit(0)
	except dbus.DBusException, e:
                print " unable to set topic of cbs %s" % e
                sys.exit(1)

if sys.argv[1] == 'properties':
	try:
		properties = cb.GetProperties()
		for key in properties.keys():
			print "  %s = %s" % (key, properties[key])
		sys.exit(0)
        except dbus.DBusException, e:
                print " unable to get properties of cbs %s" % e
                sys.exit(1)
	
print "Unknown command"
sys.exit(1)

