#!/usr/bin/python
## Copyright (C) 2008-2010, Intel Corporation.
# DESCR: oFono sms test script
# TIMEOUT:60
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307 USA.
#
# Authors:
#       Li,Zhigang  <zhigang.li@intel.com>
#

import sys
import dbus

def print_useage(s):
	print "Useage: %s <sc>  <value>" % (s)
	print "Useage: %s <send> <number> <content>" % (s)
	print "Useage: %s <enable-reports> " % (s)
	print "Useage: %s <disable-reports> " % (s)
	print "Useage: %s <bearer> [cs-only,ps-only,cs-preferred,ps-preferred]" % (s)
	print "Useage: %s properties " % (s)
	sys.exit(1);

if len(sys.argv) < 3 and len(sys.argv) != 2:
	print_useage(sys.argv[0])

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
		'org.ofono.Manager')



modems = manager.GetModems()
path=modems[0][0]


sms = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.MessageManager')


if (sys.argv[1] == 'sc'):
	print "set service center address"
	address = sys.argv[2]
	try:
		sms.SetProperty("ServiceCenterAddress", address)
		print sms.GetProperties()
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set sms center address: ", e
		sys.exit(1)

if (sys.argv[1] == 'enable-reports'):
	try:
		sms.SetProperty("UseDeliveryReports", dbus.Boolean(1))
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to enable sms delivery reports: ", e
		sys.exit(1)

if (sys.argv[1] == 'disable-reports'):
	try:
		sms.SetProperty("UseDeliveryReports", dbus.Boolean(0))
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to disable sms delivery reports: ", e
		sys.exit(1)

if (sys.argv[1] == 'bearer'):
	try:
		sms.SetProperty("Bearer", sys.argv[2])
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set bearer for sms: ", e
		sys.exit(1)

if (sys.argv[1] == 'properties'):
	try:
		print sms.GetProperties()
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to get sms properties: ", e
		sys.exit(1)

if (sys.argv[1] == 'send'):
	try:
		sms.SendMessage(sys.argv[2], sys.argv[3])
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to send a sms: ", e
		sys.exit(1)

print "Unkonown command:"
sys.exit(1)
