#!/usr/bin/python
# Copyright (C) 2008-2010, Intel Corporation.
# DESCR: oFono call volume test script
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307 USA.
#
# Authors:
#       Li,Zhigang  <zhigang.li@intel.com>
#


import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
modems = manager.GetProperties()['Modems']

volume = dbus.Interface(bus.get_object('org.ofono', modems[0]),
			'org.ofono.CallVolume')

if len(sys.argv) < 2:
	print """Usage: %s <command>
	properties
	set <SpeakerVolume,Mute> <value>
	"MicrophoneVolume not support yet"
	""" % sys.argv[0]
	sys.exit(1)

if sys.argv[1] == "properties":
	try:
		properties = volume.GetProperties()
	except dbus.DBusException, e:
		print "Unable to get the property: ", e
		sys.exit(1)

       	print "	Microphone value =  '%d'" % (properties['MicrophoneVolume'])
	print "	Speaker value =  '%d'" % (properties['SpeakerVolume'])
	if properties['Muted']:
		print "	Mute is on'"
	else:
		print "	Mute is off"
	sys.exit(0)

if sys.argv[1] == "set":
	try:
		if sys.argv[2] == "Mute":
			volume.SetProperty("Muted",True)
			sys.exit(0)
		else:
			volume.SetProperty(sys.argv[2], dbus.Byte(int(sys.argv[3])))
			sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set the property: ", e
		sys.exit(1)

print "Unknown command:"
sys.exit(1)
