#!/bin/sh
# kill-telepathy - Script for removing telepathy framework from N900
#
#  Copyright (C) 2000-2010, Nokia Corporation.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 2.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#moving service file to different location
mv /usr/share/dbus-1/services/org.freedesktop.Telepathy.ConnectionManager.ring.service  /usr/share/dbus-1/services/org.freedesktop.Telepathy.ConnectionManager.ring.service.old

#and kill telepathy
killall -HUP dbus-daemon
killall telepathy-ring
killall -HUP mission-control

