#!/usr/bin/python
# Copyright (C) 2008-2010, Intel Corporation.
# DESCR: oFono Supplementary Service setting test
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307 USA.
#
# Authors:
#       Li,Zhigang  <zhigang.li@intel.com>
#
#


import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
                                        'org.ofono.Manager')

modems = manager.GetProperties()['Modems']

cf = dbus.Interface(bus.get_object('org.ofono', modems[0]),
                                        'org.ofono.CallForwarding')

cs = dbus.Interface(bus.get_object('org.ofono', modems[0]),
                                        'org.ofono.CallSettings')

if len(sys.argv) < 2:
	print """ Usage: %s <command> <number>
	VoiceBusy	<number>
	VoiceUnconditional	<number>
	VoiceNoReply	<number>
	VoiceNotReachable	<number>
	DataUnconditional	<number>
	DataBusy	<number>
	DataNoReply	<number>
	DataNotReachable	<number>
	FaxUnconditional	<number>
	FaxBusy	<number>
	FaxNoReply	<number>
	FaxNotReachable	<number>
	SmsUnconditional	<number>
	SmsBusy	<number>
	SmsNoReply	<number>
	SmsNotReacahable	<number>
	VoiceNoReplyTimeout <20, 30>
	disable <all,conditional>
	HideCallerId <enabled, disabled>
	VoiceCallWaiting <enabled, disabled>
	""" % sys.argv[0]
        sys.exit(1)

if sys.argv[1] == "disable":
	try:
		cf.DisableAll(sys.argv[2])
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set setting - Good: ", e
		sys.exit(1)

if (sys.argv[1] == "HideCallerId") or (sys.argv[1] == "VoiceCallWaiting"):
	try:
		cs.SetProperty(sys.argv[1], sys.argv[2])
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set setting - Good: ", e
		sys.exit(1)

else:
	timeout = sys.argv[2]
	if sys.argv[1] == "VoiceNoReplyTimeout":
                timeout = dbus.UInt16(sys.argv[2])

	try:
		cf.SetProperty(sys.argv[1], timeout)
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set call forward Properties - Good: ", e
		sys.exit(1)

print "unknown command:"
sys.exit(1)

