#!/usr/bin/python
# Copyright (C) 2008-2010, Intel Corporation.
# DESCR: oFonon ready phonebook in modem test script
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307 USA.

# Authors:
#       Li,Zhigang  <zhigang.li@intel.com>


import dbus
import sys

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
modems = manager.GetModems()
phonebook = dbus.Interface(bus.get_object('org.ofono', modems[0][0]),
			'org.ofono.Phonebook')

try:
	#this only for test automation
	print  unicode(phonebook.Import()).encode("utf-8")
	sys.exit(0)
except dbus.DBusException, e:
	print"Unable to get the phonebook information in Modems %s" % e
	sys.exit(1)
