#!/usr/bin/python
# Copyright (C) 2008-2010, Intel Corporation.
# DESCR: oFono Modem test script
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA 02111-1307 USA.
#
# Authors:
#       Li,Zhigang  <zhigang.li@intel.com>
#
#

import sys
import dbus

def print_useage(s):
	print "Useage: %s poweron [number]" % (s)
	print "Useage: %s poweroff [number]" % (s)
	print "Useage: %s online" % (s)
	print "Useage: %s offline" % (s)
	print "Useage: %s properties" % (s)

if len(sys.argv) < 2:
	print_useage(sys.argv[0])
	sys.exit(1)

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
		'org.ofono.Manager')

modems = manager.GetModems()

p = 0
if len(sys.argv) == 3:
	p = int(sys.argv[2])

modem = dbus.Interface(bus.get_object('org.ofono', modems[p][0]),
						'org.ofono.Modem')

if (sys.argv[1] == 'properties'):

	try:
		properties = modem.GetProperties()
	except dbus.DBusException, e:
		print "Unable to get the property: ", e
		sys.exit(1)

	for key in properties.keys():
			print "  %s = %s" % (key, properties[key])
	sys.exit(0)

if (sys.argv[1] == 'poweron'):
	try:
		modem.SetProperty("Powered",True)
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set the property: ", e
		sys.exit(1)

if (sys.argv[1] == 'poweroff'):
	try:
		modem.SetProperty("Powered",False)
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set the property: ", e
		sys.exit(1)

if (sys.argv[1] == 'online'):
	try:
		modem.SetProperty("Online",True)
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set the property: ", e
		sys.exit(1)

if (sys.argv[1] == 'offline'):
	try:
		modem.SetProperty("Online",False)
		sys.exit(0)
	except dbus.DBusException, e:
		print "Unable to set the property: ", e
		sys.exit(1)

print "Unknown command"
sys.exit(1)

